add_menu_dialog.c: In function `add_menu_cb': add_menu_dialog.c:68: Warnung: implicit declaration of function `create_header' add_menu_dialog.c:68: Warnung: assignment makes pointer from integer without a cast add_menu_dialog.c:152: Warnung: implicit declaration of function `strlen' add_menu_dialog.c:125: Warnung: unused variable `root_iter'
(Old svn revision: 7576)